# Generated by Django 2.2.6 on 2020-11-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_auto_20201101_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hostel_b',
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal',
        ),
        migrations.AlterField(
            model_name='student',
            name='own_vehicle',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.CASCADE, to='hostel_app.CollegeInfo'),
        ),
    ]
