# Generated by Django 2.2.6 on 2020-11-03 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_auto_20201101_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='wardenInfo',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=7, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, null=True)),
                ('phone_no', models.BigIntegerField(db_column='PHONE_NO', null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('slot', models.CharField(choices=[('M', 'Morning'), ('N', 'Night')], default=None, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='b_phone_no',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='totroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='mis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.CollegeInfo'),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='branch',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(max_length=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='wardeninfo',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.Hostel'),
        ),
    ]
