# Generated by Django 2.2.6 on 2020-11-04 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_auto_20201103_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinfo',
            name='batchof',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='mis',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mess',
            name='contractor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mess',
            name='daily_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mis_id',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='hostel_app.CollegeInfo'),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='name',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
