# Generated by Django 2.2.6 on 2020-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_auto_20201104_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
    ]
