# Generated by Django 2.2.6 on 2020-11-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_auto_20201104_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardeninfo',
            name='hostel',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.wardenInfo'),
        ),
    ]
